{% set version = "4.2.1" %}
{% set name = "givaro" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/linbox-team/givaro/archive/v{{ version }}.tar.gz
  sha256: 6aae4b74c2772b6f4aa4e55d1d90f79214635aa664e3b121dde2e0b5192f310b
  patches:
    - 0001-Do-not-run-test-programs-when-cross-compiling.patch

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('givaro', max_pin='x.x.x') }}

requirements:
  build:
    - libtool   # [unix]
    - autoconf  # [unix]
    - automake  # [unix]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - libtool
    - make
  host:
    - gmp
  run:

test:
  commands:
    - test -f ${PREFIX}/include/givaro/givaromm.h
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so     # [linux]

about:
  home: https://casys.gricad-pages.univ-grenoble-alpes.fr/givaro/
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: Givaro - C++ library for arithmetic and algebraic computations
  dev_url: https://github.com/linbox-team/givaro
  doc_url: https://casys.gricad-pages.univ-grenoble-alpes.fr/givaro/givaro-html/

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
