{% set version = "4.2.0" %}
{% set name = "givaro" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/linbox-team/givaro/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 865e228812feca971dfb6e776a7bc7ac959cf63ebd52b4f05492730a46e1f189
  patches:
    - cross.diff

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('givaro', max_pin='x.x.x') }}

requirements:
  build:
    - libtool   # [unix]
    - autoconf  # [unix]
    - automake  # [unix]
    - {{ compiler('cxx') }}
    - libtool
    - make
  host:
    - gmp

test:
  commands:
    - test -f ${PREFIX}/include/givaro/givaromm.h
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so     # [linux]

about:
  home: http://givaro.forge.imag.fr
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: Givaro - C++ library for arithmetic and algebraic computations
  dev_url: https://github.com/linbox-team/givaro
  doc_url: http://givaro.forge.imag.fr/givaro-html

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
